packageExtensions:
  "@celo/connect@*":
    dependencies:
      "@celo/base": "*"
      web3-eth-contract: "*"
      web3-utils: "*"
  "@celo/contractkit@*":
    dependencies:
      web3-utils: "*"
  "@celo/utils@*":
    dependencies:
      randombytes: "*"
      rlp: "*"
  "@typechain/hardhat@*":
    dependencies:
      lodash: "*"
      typechain: "*"
  "@ubeswap/hardhat-celo@*":
    dependencies:
      "@celo/contractkit": "*"
      "@nomiclabs/hardhat-ethers": "*"
  "@ubeswap/sdk@*":
    dependencies:
      "@ethersproject/address": "*"
      "@ethersproject/contracts": "*"
      "@ethersproject/networks": "*"
      "@ethersproject/providers": "*"
      "@ethersproject/solidity": "*"
  typechain@*:
    dependencies:
      "@typechain/web3-v1": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

pnpIgnorePatterns:
  - ./ng-packages/**

yarnPath: .yarn/releases/yarn-3.2.0-rc.6.cjs
