packageExtensions:
  "@celo/base@*":
    dependencies:
      bignumber.js: "*"
  "@celo/connect@*":
    dependencies:
      "@celo/base": "*"
      web3-eth-contract: "*"
      web3-utils: "*"
  "@celo/contractkit@*":
    dependencies:
      web3-utils: "*"
  "@celo/utils@*":
    dependencies:
      randombytes: "*"
      rlp: "*"
  "@celo/wallet-ledger@*":
    dependencies:
      "@celo/base": "*"
      "@ledgerhq/errors": "*"
  "@celo/wallet-walletconnect@*":
    dependencies:
      "@celo/base": "*"
      "@walletconnect/utils": "*"
  "@json-rpc-tools/provider@*":
    dependencies:
      tslib: "*"
  "@json-rpc-tools/types@*":
    dependencies:
      tslib: "*"
  "@json-rpc-tools/utils@*":
    dependencies:
      tslib: "*"
  "@poofcash/use-contractkit@*":
    dependencies:
      bignumber.js: "*"
      web3: "*"
  "@typechain/hardhat@*":
    dependencies:
      lodash: "*"
      typechain: "*"
  "@ubeswap/hardhat-celo@*":
    dependencies:
      "@celo/contractkit": "*"
      "@nomiclabs/hardhat-ethers": "*"
  "@ubeswap/sdk@*":
    dependencies:
      "@ethersproject/address": "*"
      "@ethersproject/contracts": "*"
      "@ethersproject/networks": "*"
      "@ethersproject/providers": "*"
      "@ethersproject/solidity": "*"
  "@walletconnect/client@*":
    dependencies:
      tslib: "*"
  "@walletconnect/types@*":
    dependencies:
      tslib: "*"
  babel-preset-react-app@*:
    dependencies:
      "@babel/plugin-proposal-private-property-in-object": "*"
  graphql-request@*:
    dependencies:
      graphql: "*"
  typechain@*:
    dependencies:
      "@typechain/web3-v1": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

pnpIgnorePatterns:
  - ./ng-packages/**

nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-3.1.1.cjs
enableProgressBars: true
progressBarStyle: simba
