/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { SwayAdmin, SwayAdminInterface } from "../SwayAdmin";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_addr",
        type: "address",
      },
    ],
    name: "isGovernor",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class SwayAdmin__factory {
  static readonly abi = _abi;
  static createInterface(): SwayAdminInterface {
    return new utils.Interface(_abi) as SwayAdminInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SwayAdmin {
    return new Contract(address, _abi, signerOrProvider) as SwayAdmin;
  }
}
